# Generated by Django 5.2 on 2026-08-18 18:34

import core.utils
import post.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('text', models.TextField(max_length=700, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('file', models.FileField(upload_to=post.utils.MediaUtils.media_upload_to, verbose_name='Медиа')),
                ('file_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=20, verbose_name='Тип файла')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('is_for_stream', models.BooleanField(default=True, verbose_name='Для стрима')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('reason', models.CharField(choices=[('adult', 'Контент 18+'), ('illegal', 'Незаконный'), ('advertising', 'Реклама'), ('spam', 'Спам'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('other', models.TextField(blank=True, max_length=700, verbose_name='Другое')),
                ('status', models.CharField(choices=[('not_viewed', 'Не рассмотрена'), ('approved', 'Одобрена'), ('rejected', 'Отменена')], default='not_viewed', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Репорт',
                'verbose_name_plural': 'Репорты',
                'ordering': ['-created_at'],
            },
        ),
    ]
