# Generated by Django 5.2 on 2026-08-18 18:34

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('public_id', models.CharField(default=core.utils.generate_public_id, editable=False, max_length=8, unique=True, verbose_name='Public ID')),
                ('youtube_id', models.CharField(max_length=11, unique=True, verbose_name='YouTube ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('preview_url', models.URLField(verbose_name='Превью')),
                ('channel_name', models.CharField(max_length=100, verbose_name='Канал')),
                ('pub_date', models.DateTimeField(verbose_name='Опубликовано на YouTube')),
                ('duration', models.SmallIntegerField(verbose_name='Длительность в секундах')),
                ('views_count', models.PositiveBigIntegerField(verbose_name='Просмотры')),
                ('likes_count', models.PositiveIntegerField(verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(verbose_name='Коммы из Youtube')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Бан')),
                ('category', models.CharField(choices=[('humurous', 'Смешные'), ('truecrime', 'Трукрайм'), ('cognitive', 'Познавательные'), ('trailers', 'Трейлеры'), ('different', 'Разное')], max_length=20, verbose_name='Категория')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='Комментарий автора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_videos', to=settings.AUTH_USER_MODEL, verbose_name='Голоса')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='youtube_suggestion.video', verbose_name='Голоса')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='youtube_sug_categor_34c769_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['video'], name='youtube_sug_video_i_eb0ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['user'], name='youtube_sug_user_id_1ae17e_idx'),
        ),
        migrations.AddConstraint(
            model_name='voting',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_user_video_voting'),
        ),
    ]
